# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Maxime Van den Kerkhof
tagline: 'Apps & Projects'
description: 'iOS apps by Maxime Van den Kerkhof'
url: https://maximevdk.github.io
baseurl: ""

author:
  name: 'Maxime Van den Kerkhof'

# Build settings
exclude:
  - README.md
  - LICENSE.md
