# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Connected Abroad
tagline: 'Stay connected with family back home'
description: 'An iOS app to help expats stay connected with family through easy photo sharing and messaging reminders.'
url: https://maximevdk.github.io
baseurl: /

author:
  name: 'Maxime Van den Kerkhof'

# Build settings
exclude:
  - README.md
  - LICENSE.md
